name: signedcontainer-$(Build.BuildId)

trigger:
- trust

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: securecontainervars
- name: keyfingerprint
  value: 865d649308dc194b52a9236ebf6811252fad356fac73d44c10bcd9c1361402fd
- name: containerRegistryServiceConnection
  value: mjgk8sacr
- name: imageRepository
  value: secure/voting/app
- name: tag
  value: 2.0.$(Build.BuildId)-signed

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(containerRegistryServiceConnection)

- script: |
    mkdir -p $(DOCKER_CONFIG)/trust/private
    echo "$(devops-signing-key)" > $(DOCKER_CONFIG)/trust/private/$(keyfingerprint).key

- task: Docker@2
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    containerRegistry: $(containerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: |
      $(tag)
    arguments: '--disable-content-trust=false'

- task: Docker@2
  inputs: 
    command: push
    containerRegistry: $(containerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: |
      $(tag)
    arguments: '--disable-content-trust=false'
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: $(devops-passphrase)